version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: mxtz
      DB_PASSWORD: mxtz2023
      DB_NAME: api_nest
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: api_nest
      MYSQL_USER: mxtz
      MYSQL_PASSWORD: mxtz2023
      MYSQL_ROOT_PASSWORD: mxtz2023
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
